Repository Innostax/tavajs, pull requests merged in 2022-10, with the labels that each got.

#266 138/Add CSS tailwind framework for vue app.
  src/Frameworks/CSSFrameworks/TailwindCSSFramework/vue/postcss.config.js
  src/Frameworks/CSSFrameworks/TailwindCSSFramework/vue/tailwind.config.js
  src/Frameworks/WebFrameworks/vue/package.json
  src/Frameworks/WebFrameworks/vue/src/App.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/atoms/Button.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/atoms/Input.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/atoms/Label.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/atoms/LogoutButton.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/organisms/Modal.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/organisms/Navbar.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/organisms/Table.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/pages/Home.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/pages/Users.vue
  src/Frameworks/WebFrameworks/vue/src/bootstrap/styles/dark-theme.css
  src/Frameworks/WebFrameworks/vue/src/bootstrap/styles/index.css
  src/Frameworks/WebFrameworks/vue/src/main.js
  src/Frameworks/WebFrameworks/vue/src/tailwind/components/atoms/Button.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/components/atoms/Input.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/components/atoms/Label.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/components/atoms/LogoutButton.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/components/organisms/Modal.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/components/organisms/Navbar.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/components/organisms/Table.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/pages/Home.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/pages/Users.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/styles/index.css
  src/Providers/ThemeProviders/vue-themes/theme.vue
  src/Services/NetworkInformerServices/vue/NetworkStatus/NetworkStatus.vue
  src/Services/NetworkInformerServices/vue/NetworkStatus/network-status.css
  src/StateManagement/ngrxTemplates/store/action/user.actions.spec.ts
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.spec.ts
  src/StateManagement/vuexTemplates/bootstrap/userModal/AddUser.vue
  src/StateManagement/vuexTemplates/bootstrap/userModal/DeleteUser.vue
  src/StateManagement/vuexTemplates/bootstrap/userModal/EditUser.vue
  src/StateManagement/vuexTemplates/bootstrap/userModal/ShowUsers.vue
  src/StateManagement/vuexTemplates/tailwind/userModal/AddUser.vue
  src/StateManagement/vuexTemplates/tailwind/userModal/DeleteUser.vue
  src/StateManagement/vuexTemplates/tailwind/userModal/EditUser.vue
  src/StateManagement/vuexTemplates/tailwind/userModal/ShowUsers.vue
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/constants.js
  src/TavaJsExecutors/dependencies.js
  src/utils/helper.js
Labels: Enhancement, Ready

#292 Terminal spinner should not blink.
  package.json
  src/utils/projectSetUp.js
Labels: Bug, Ready

#293 290/Update message and time displayed for successful project creation.
  src/utils/projectSetUp.js
Labels: Improvement, Ready

#300 295/Update modal name for vicemodal to tavajsmodal.
  src/Frameworks/WebFrameworks/react/src/components/bootstrap/organisms/Modal.js
  src/Frameworks/WebFrameworks/react/src/components/material/organisms/Modal.js
  src/Frameworks/WebFrameworks/react/src/components/tailwind/organisms/Modal.js
  src/StateManagement/reduxTemplates/userform/DeleteConfirmationModal.js
  src/StateManagement/reduxTemplates/widgets/modal/Modal.js
  src/utils/helper.js
Labels: Improvement, Ready

#299 294/Use reusable Input component for userModals in vue.
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/atoms/Input.vue
  src/StateManagement/vuexTemplates/bootstrap/userModal/AddUser.vue
  src/StateManagement/vuexTemplates/bootstrap/userModal/EditUser.vue
Labels: Bug, Ready

#301 258/Added CI/CD pipeline for (Angular/React/Vue) App.
  src/Providers/CICDWorkflow/angular-build.yml
  src/Providers/CICDWorkflow/react-build.yml
  src/Providers/CICDWorkflow/vue-build.yml
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/constants.js
  src/TavaJsExecutors/questionnaire.js
  src/utils/helper.js
  src/utils/projectSetUp.js
Labels: Enhancement, Ready

#302 297/Refactor crud implementation for react
  src/Frameworks/WebFrameworks/react/src/screens/Users/Users.js
  src/StateManagement/reduxTemplates/demoUser/users.actions.js
  src/StateManagement/reduxTemplates/usersModal/userModal.constants.js
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/questionnaire.js
  src/utils/helper.js
Labels: Improvement, Ready

#298 Added Github workflows for test cases scripts in TAVAJS
  .github/workflows/test.cases.yml
  package.json
  test/test.spec.js
Labels: Enhancement, Ready

#308 303/Implement CI/CD pipeline for angular app using aws.
  src/Frameworks/WebFrameworks/angular/angular.json
  src/Providers/CICDWorkflow/angular-build.yml
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/constants.js
  src/TavaJsExecutors/questionnaire.js
  src/utils/helper.js
Labels: Enhancement, Ready

#314 309/Implemented CI/CD pipeline for react app using aws.
  src/Providers/CICDWorkflow/react-build.yml
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/constants.js
  src/utils/helper.js
Labels: Ready

#315 296/Refactor CRUD implementation for vue.
  src/StateManagement/vuexTemplates/bootstrap/userModal/ShowUsers.vue
  src/StateManagement/vuexTemplates/store/modules/users.js
  src/StateManagement/vuexTemplates/tailwind/userModal/ShowUsers.vue
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/questionnaire.js
Labels: Improvement, Ready

#317 310/Updated project info options are shown in project creation.
  src/Frameworks/WebFrameworks/angular/angular.json
  src/Frameworks/WebFrameworks/angular/karma.conf.js
  src/utils/projectInfo.js
Labels: Improvement, Ready

#326 323/Fix delete confirmation modal refactoring issue
  src/Frameworks/WebFrameworks/react/src/components/bootstrap/organisms/Modal.js
  src/Frameworks/WebFrameworks/react/src/components/material/organisms/Modal.js
  src/Frameworks/WebFrameworks/react/src/components/tailwind/organisms/Modal.js
  src/Frameworks/WebFrameworks/react/src/screens/Users/Users.js
  src/StateManagement/reduxTemplates/userform/AddUserForm.js
  src/StateManagement/reduxTemplates/userform/Adduser.js
  src/StateManagement/reduxTemplates/userform/DeleteConfirmationModal.js
Labels: Bug, Ready

#330 329/Integrate prettier for vue app.
  src/Frameworks/WebFrameworks/angular/package.json
  src/Frameworks/WebFrameworks/vue/package.json
Labels: Improvement, Ready

#324 322/Fix issue of project setup commands not visible for yarn package manager
  src/Frameworks/BackendFrameworks/node-js/.prettierignore
  src/Frameworks/WebFrameworks/react/.prettierignore
  src/Frameworks/WebFrameworks/react/package.json
  src/utils/projectSetUp.js
Labels: Improvement, Ready

#321 155/Add Material UI for angular app.
  src/Frameworks/CSSFrameworks/MaterialUIFramework/angular/custom-materialui.module.ts
  src/Frameworks/WebFrameworks/angular/angular.json
  src/Frameworks/WebFrameworks/angular/src/app/app.module.ts
  src/Frameworks/WebFrameworks/angular/src/app/pages/header/header.component.css
  src/Frameworks/WebFrameworks/angular/src/app/pages/header/header.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/header/header.component.ts
  src/Frameworks/WebFrameworks/angular/src/app/pages/home/home.component.css
  src/Frameworks/WebFrameworks/angular/src/app/pages/home/home.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/users/users.component.css
  src/Frameworks/WebFrameworks/angular/src/app/pages/users/users.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/users/users.component.ts
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/atoms/button/button.component.css
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/atoms/button/button.component.html
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/atoms/button/button.component.ts
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/atoms/input/input.component.css
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/atoms/input/input.component.html
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/molecules/table/table.component.css
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/molecules/table/table.component.html
  src/Frameworks/WebFrameworks/angular/src/app/shared/shared.module.ts
  src/Frameworks/WebFrameworks/angular/src/index.html
  src/Frameworks/WebFrameworks/angular/src/styles.css
  src/Providers/ThemeProviders/angular-themes/dark-theme.css
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.css
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.html
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/dependencies.js
  src/utils/helper.js
  src/utils/projectInfo.js
Labels: Enhancement, Ready

#331 305/fix UI of navbar in react app
  src/Frameworks/WebFrameworks/react/src/App.css
  src/Frameworks/WebFrameworks/react/src/components/bootstrap/organisms/NavBar.js
  src/Frameworks/WebFrameworks/react/src/components/material/organisms/NavBar.js
  src/Frameworks/WebFrameworks/react/src/components/tailwind/organisms/NavBar.js
  src/Providers/ThemeProviders/react-themes/theme.js
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/constants.js
  src/utils/helper.js
  src/utils/projectSetUp.js
Labels: Improvement, Ready

#334 328/Update readme of angular application
  src/Frameworks/WebFrameworks/angular/README.md
  src/TavaJsExecutors/answersEvaluator.js
  src/utils/helper.js
Labels: Improvement, Ready

#333 Input fields should reset when cancel button is clicked on Bootstrap EditUser modal.
  src/Frameworks/WebFrameworks/vue/src/bootstrap/components/organisms/Modal.vue
  src/StateManagement/vuexTemplates/bootstrap/userModal/EditUser.vue
  src/TavaJsExecutors/constants.js
Labels: Bug, Ready

#339 338/Fix docker for Vue app.
  src/Services/DockerServices/vue-docker/Dockerfile
  src/TavaJsExecutors/answersEvaluator.js
Labels: Bug, Ready

#341 340/Update dependencies of react
  src/Frameworks/WebFrameworks/react/package.json
  src/Frameworks/WebFrameworks/react/src/components/tailwind/organisms/NavBar.js
  src/TavaJsExecutors/dependencies.js
Labels: Improvement, Ready

#345 344/Update readme file for vue app.
  README.md
  src/Frameworks/WebFrameworks/vue/README.md
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/constants.js
  src/utils/helper.js
Labels: Improvement, Ready

#304 228/automate qa of tavajs latest - TC0001
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  src/Frameworks/WebFrameworks/react/src/App.js
  src/TavaJsExecutors/answersEvaluator.js
  src/dockerTemplate/angular-docker/.dockerignore
  src/index.js
  src/utils/projectExecutionCommands.js
  src/utils/projectInfo.js
  src/utils/projectSetUp.js
  test/test.spec.js
  tests/helpers.js
  tests/mockData.js
  tests/test-cases/TC0001.js
  tests/test-cases/TC0002.js
  tests/test-cases/TC0003.js
  tests/test-cases/TC0004.js
  tests/test-cases/TC0005.js
Labels: Enhancement, Ready

#347 346/Updated_tavajs-readme_angular-Readme_angular-UI
  README.md
  src/Frameworks/WebFrameworks/angular/README.md
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.css
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.html
Labels: Improvement, Ready

#349 Updated readme file for react app
  src/Frameworks/WebFrameworks/react/README.md
Labels: Improvement, Ready

#352 228/ Automate QA for react, angular & vue.
  .github/workflows/test.cases.yml
  package-lock.json
  package.json
  src/utils/projectExecutionCommands.js
  src/utils/projectInfo.js
  src/utils/projectSetUp.js
  tests/helpers.js
  tests/mockData.js
  tests/test-cases/TC0001.js
  tests/test-cases/TC0002.js
  tests/test-cases/TC0003.js
  tests/test-cases/TC0004.js
  tests/test-cases/TC0005.js
  tests/test-cases/TC0006.js
  tests/test-cases/TC0007.js
  tests/test-cases/TC0008.js
  tests/test-cases/TC0009.js
  tests/test-cases/TC0010.js
  tests/test-cases/TC0011.js
  tests/test-cases/TC0012.js
  tests/test-cases/TC0013.js
  tests/test-cases/TC0014.js
Labels: Improvement, Ready

#359 353/Remove crud question from angular application
  src/Frameworks/WebFrameworks/angular/package.json
  src/Frameworks/WebFrameworks/angular/src/app/app.module.ts
  src/Frameworks/WebFrameworks/angular/src/app/pages/header/header.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/users/users.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/users/users.component.ts
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/atoms/input/input.component.css
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/molecules/table/table.component.html
  src/Frameworks/WebFrameworks/angular/src/app/shared/shared.module.ts
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.css
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.html
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.ts
  src/StateManagement/reduxTemplates/usersModal/index.js
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/questionnaire.js
  src/utils/helper.js
Labels: Improvement, Ready

#351 350/User modals should not be present when vuex is not selected.
  src/Frameworks/WebFrameworks/vue/README.md
  src/Frameworks/WebFrameworks/vue/src/tailwind/pages/Users.vue
  src/Services/BlobServices/azure.js
Labels: Bug, Ready

#358 Refactor CRUD for react app
  src/Frameworks/CSSFrameworks/React/tailwind/organisms/NavBar.js
  src/Frameworks/WebFrameworks/react/src/App.css
  src/Frameworks/WebFrameworks/react/src/screens/Users/Users.js
  src/StateManagement/reduxTemplates/demoUser/users.actions.js
  src/StateManagement/reduxTemplates/infrastructure/httpMethods/requestingMethods.js
  src/TavaJsExecutors/answersEvaluator.js
Labels: Improvement, Ready

#361 Refactored React code
  src/Frameworks/CSSFrameworks/React/material/atoms/Label.js
  src/StateManagement/reduxTemplates/userform/AddUserForm.js
  src/StateManagement/reduxTemplates/userform/Adduser.js
  src/StateManagement/reduxTemplates/usersModal/ShowDetails.js
  src/StateManagement/reduxTemplates/usersModal/userModal.constants.js
  src/StateManagement/reduxTemplates/widgets/modal/Modal.js
  src/StateManagement/reduxTemplates/widgets/modal/index.js
  src/StateManagement/reduxTemplates/widgets/modal/modal.selectors.js
  src/StateManagement/reduxTemplates/widgets/modal/modal.slice.js
  src/TavaJsExecutors/answersEvaluator.js
Labels: Improvement, Ready

#368 Refactor TavaJs code
  src/Environments/BackendEnvironment/.sendgrid
  src/Environments/BackendEnvironment/.smtp
  src/Generators/RouteGenerator/generate-route.js
  src/Generators/ScreenGenerator/generate-react-screen.js
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/dependencies.js
  src/TavaJsExecutors/questionnaire.js
  src/TavaJsExecutors/scripts.js
  src/index.js
  src/utils/helper.js
  tests/test-cases/TC0001.js
  tests/test-cases/TC0002.js
  tests/test-cases/TC0003.js
  tests/test-cases/TC0004.js
  tests/test-cases/TC0005.js
Labels: Improvement, Ready

#369 365/Refactor test cases functionality in tavajs
  package.json
  src/Generators/RouteGenerator/generate-route.js
  src/utils/getProjectDetails.js
  src/utils/helper.js
  tests/helpers.js
  tests/mockData.js
  tests/test-cases/TC0001.js
  tests/test-cases/TC0002.js
  tests/test-cases/TC0003.js
  tests/test-cases/TC0004.js
  tests/test-cases/TC0005.js
  tests/test-cases/TCA001.js
  tests/test-cases/TCA002.js
  tests/test-cases/TCA003.js
  tests/test-cases/TCN001.js
  tests/test-cases/TCR001.js
  tests/test-cases/TCR002.js
  tests/test-cases/TCR003.js
  tests/test-cases/TCV001.js
  tests/test-cases/TCV002.js
  tests/test-cases/TCV003.js
Labels: Improvement, Ready

#370 367/Refactor UI changes in angular app
  src/Frameworks/WebFrameworks/angular/src/app/pages/header/header.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/pages-routing.module.ts
  src/Frameworks/WebFrameworks/angular/src/app/pages/users/users.component.html
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/molecules/table/table.component.html
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.html
Labels: Improvement, Ready

#371 Fix no env generated for backend with Docker
  src/TavaJsExecutors/answersEvaluator.js
Labels: Bug, Ready

#372 Update frontend and backend docker file for yarn commands
  src/Frameworks/BackendFrameworks/node-js/package.json
  src/Frameworks/WebFrameworks/angular/package.json
  src/Services/DockerServices/angular-docker/.dockerignore
  src/Services/DockerServices/angular-docker/Dockerfile
  src/Services/DockerServices/react-docker/Dockerfile
  src/Services/DockerServices/vue-docker/.dockerignore
  src/Services/DockerServices/vue-docker/Dockerfile
  src/TavaJsExecutors/answersEvaluator.js
  src/utils/helper.js
Labels: Improvement, Ready

#374 Update buildyml in github workflows directory for backend cicd integration
  src/Frameworks/BackendFrameworks/node-js/package.json
  src/Frameworks/WebFrameworks/angular/.prettierignore
  src/Frameworks/WebFrameworks/react/.prettierignore
  src/Providers/CICDWorkflow/angular-build.yml
  src/Providers/CICDWorkflow/react-build.yml
  src/Providers/CICDWorkflow/vue-build.yml
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/constants.js
Labels: Improvement, Ready

#375 373/Implement generate new screen for frontend application
  package.json
  src/Frameworks/WebFrameworks/angular/src/app/app.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/header/header.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/header/header.component.ts
  src/Frameworks/WebFrameworks/angular/src/app/pages/home/home.component.html
  src/Frameworks/WebFrameworks/angular/src/app/pages/pages.module.ts
  src/Frameworks/WebFrameworks/angular/src/app/pages/users/users.component.html
  src/Frameworks/WebFrameworks/vue/src/bootstrap/pages/Home.vue
  src/Frameworks/WebFrameworks/vue/src/router/index.js
  src/Frameworks/WebFrameworks/vue/src/tailwind/components/organisms/Navbar.vue
  src/Frameworks/WebFrameworks/vue/src/tailwind/pages/Home.vue
  src/Generators/ScreenGenerator/ScreenTemplates/react/index.js
  src/Generators/ScreenGenerator/ScreenTemplates/react/screen.constant.js
  src/Generators/ScreenGenerator/ScreenTemplates/react/screen.js
  src/Generators/ScreenGenerator/ScreenTemplates/react/screen.utils.js
  src/Generators/ScreenGenerator/ScreenTemplates/vue/screen.vue
  src/Generators/ScreenGenerator/generate-react-screen.js
  src/Generators/ScreenGenerator/generate-screen.js
  src/Generators/ScreenGenerator/screenTemplates/index.js
Labels: Improvement, Ready

#376 366/Fix issues of generate routes
  src/Generators/RouteGenerator/controllers/mongoose.controllers.js
  src/Generators/RouteGenerator/controllers/mysql.controllers.js
  src/Generators/RouteGenerator/controllers/postgres.controllers.js
  src/Generators/RouteGenerator/generate-route.js
  src/Generators/RouteGenerator/models/mongoose.models.js
  src/Generators/RouteGenerator/models/sequelize.models.js
  src/Generators/RouteGenerator/mongooseTemplates/route.model.js
  src/Generators/RouteGenerator/mongooseTemplates/route.routes.js
  src/Generators/RouteGenerator/postgresTemplates/route.model.js
  src/Generators/RouteGenerator/routes/route.routes.js
  src/Services/DatabaseServices/sequelize.js
  src/utils/createDbConn.js
  src/utils/helper.js
Labels: Bug, Ready

#379 377/Refactor tavajs code
  src/Environments/BackendEnvironment/.backendEnv
  src/Environments/FrontendEnvironment/.authEnv
  src/Environments/FrontendEnvironment/.cognitoEnv
  src/Environments/FrontendEnvironment/.oktaEnv
  src/Frameworks/BackendFrameworks/node-js/controllers/controller.js
  src/Frameworks/BackendFrameworks/node-js/index.js
  src/Services/DockerServices/db-docker-compose.yml
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/dependencies.js
  src/utils/converters.js
  src/utils/createBlobService.js
  src/utils/createDbConn.js
  src/utils/createEmailSevice.js
  src/utils/createLogger.js
  src/utils/helper.js
  src/utils/projectSetUp.js
Labels: Improvement, Ready

#381 380/Updated ReadMe Files
  README.md
  src/Frameworks/BackendFrameworks/node-js/.prettierignore
  src/Frameworks/WebFrameworks/angular/.prettierignore
  src/Frameworks/WebFrameworks/angular/README.md
  src/Frameworks/WebFrameworks/react/.prettierignore
  src/Frameworks/WebFrameworks/react/README.md
  src/Frameworks/WebFrameworks/vue/README.md
  src/Generators/ScreenGenerator/generate-screen.js
  src/utils/createEmailSevice.js
  src/utils/createLogger.js
Labels: Improvement, Ready
