Repository Innostax/tavajs, pull requests merged in 2022-09, with the labels that each got.

#109 102/Improve questionnaire console screen
  README.md
  src/questionnaire.js
Labels: Under Review

#110 Fix CRUD issues in VUE App
  src/templates/vue/src/components/organisms/Table.vue
  src/vuexTemplates/store/modules/users.js
  src/vuexTemplates/userModal/AddUser.vue
  src/vuexTemplates/userModal/EditUser.vue
Labels: Under Review

#112 Implement Reusable Model component for Vue template.
  src/templates/vue/src/components/organisms/Modal.vue
  src/vuexTemplates/userModal/AddUser.vue
  src/vuexTemplates/userModal/EditUser.vue
Labels: Under Review

#130 Fix NodeJS Errors.
  src/index.js
Labels: Bug, Under Review

#118 116/Add delete confirmation modal for Vue App.
  src/templates/vue/src/components/organisms/Table.vue
  src/templates/vue/src/pages/Users.vue
  src/vuexTemplates/userModal/DeleteUser.vue
  src/vuexTemplates/userModal/ShowUsers.vue
Labels: Enhancement, Under Review

#123 115/Fixed UI Issues in VUE App
  src/templates/vue/src/components/atoms/Label.vue
  src/templates/vue/src/components/organisms/Navbar.vue
  src/templates/vue/src/components/organisms/Table.vue
  src/templates/vue/src/pages/Users.vue
  src/vuexTemplates/userModal/AddUser.vue
  src/vuexTemplates/userModal/EditUser.vue
Labels: Bug, Under Review

#128 Fixed-the-Navbar-Issue-on-dark-mode
  src/templates/react/src/App.css
  src/templates/react/src/components/organisms/NavBar.js
Labels: Bug, Under Review

#125 23/OKTA Integration in React
  src/authTemplates/oktaTemplate/AppWithRouterAccess.jsx
  src/authTemplates/oktaTemplate/Home.jsx
  src/authTemplates/oktaTemplate/Protected.jsx
  src/authTemplates/oktaTemplate/SignIn.jsx
  src/authTemplates/oktaTemplate/SignInForm.jsx
  src/index.js
  src/templates/react/.eslintrc.js
  src/templates/react/package.json
  src/templates/react/src/App.js
  src/templates/react/src/components/organisms/NavBar.js
  src/utils/helper.js
Labels: Enhancement, Under Review

#120 119/Update Question for Light/Dark Theme
  src/index.js
  src/questionnaire.js
Labels: Under Review

#140 95/Integrate CRUD in Vue + Node
  src/index.js
  src/questionnaire.js
  src/vuexTemplates/doAsync/index.js
  src/vuexTemplates/httpMethod/baseurlConstant.js
  src/vuexTemplates/httpMethod/index.js
  src/vuexTemplates/store/modules/users.js
  src/vuexTemplates/userModal/AddUser.vue
  src/vuexTemplates/userModal/DeleteUser.vue
  src/vuexTemplates/userModal/EditUser.vue
  src/vuexTemplates/userModal/ShowUsers.vue
Labels: Enhancement, Under Review

#133 Implement dark mode for vue app.
  src/index.js
  src/questionnaire.js
  src/templates/vue/public/index.html
  src/templates/vue/src/App.css
  src/templates/vue/src/App.vue
  src/templates/vue/src/components/organisms/Navbar.vue
  src/templates/vue/src/pages/Users.vue
  src/themeTemplates/Theme.vue
  src/vuexTemplates/userModal/DeleteUser.vue
Labels: Enhancement, Under Review

#108 104/material UI integration final
  src/index.js
  src/questionnaire.js
  src/reduxTemplates/demoUser/users.reducer.js
  src/reduxTemplates/userform/AddUserForm.js
  src/reduxTemplates/userform/Adduser.js
  src/reduxTemplates/usersModal/ShowDetails.js
  src/reduxTemplates/widgets/modal/Modal.js
  src/templates/node-js/index.js
  src/templates/node-js/package.json
  src/templates/react/package.json
  src/templates/react/src/App.js
  src/templates/react/src/components/atoms/Label.js
  src/templates/react/src/components/bootstrap/atoms/Button.js
  src/templates/react/src/components/bootstrap/atoms/Checkbox.js
  src/templates/react/src/components/bootstrap/atoms/Datepicker.js
  src/templates/react/src/components/bootstrap/atoms/File.js
  src/templates/react/src/components/bootstrap/atoms/Input.js
  src/templates/react/src/components/bootstrap/atoms/Label.js
  src/templates/react/src/components/bootstrap/atoms/Select.js
  src/templates/react/src/components/bootstrap/molecules/InputGroup.js
  src/templates/react/src/components/bootstrap/organisms/DeleteConfirmationModal.js
  src/templates/react/src/components/bootstrap/organisms/Modal.js
  src/templates/react/src/components/bootstrap/organisms/NavBar.js
  src/templates/react/src/components/bootstrap/organisms/Table.js
  src/templates/react/src/components/material/atoms/Button.js
  src/templates/react/src/components/material/atoms/Checkbox.js
  src/templates/react/src/components/material/atoms/Datepicker.js
  src/templates/react/src/components/material/atoms/File.js
  src/templates/react/src/components/material/atoms/Input.js
  src/templates/react/src/components/material/atoms/Label.js
  src/templates/react/src/components/material/atoms/Select.js
  src/templates/react/src/components/material/molecules/InputGroup.js
  src/templates/react/src/components/material/organisms/DeleteConfirmationModal.js
  src/templates/react/src/components/material/organisms/Modal.js
  src/templates/react/src/components/material/organisms/NavBar.js
  src/templates/react/src/components/material/organisms/Table.js
  src/templates/react/src/components/organisms/Table.js
  src/templates/react/src/screens/Users/Users.js
  src/themeTemplates/themes.js
  src/utils/helper.js
Labels: Enhancement, Comments, Under Internal Review

#150 146/integrate smtp email service in react app
  src/emailTemplates/smtp.js
  src/envTemplates/.dbEnv
  src/index.js
  src/questionnaire.js
  src/templates/node-js/controllers/controller.js
  src/templates/react/src/App.js
  src/utils/helper.js
Labels: Enhancement, In Progress

#157 Migrate vue app from version 2 to version 3.
  src/templates/vue/package.json
  src/templates/vue/src/main.js
  src/templates/vue/src/router/index.js
  src/vuexTemplates/store/index.js
Labels: Improvement, Under Review

#163 Updated theme template folder structure and refactored code.
  src/index.js
  src/templates/react/src/components/bootstrap/organisms/NavBar.js
  src/templates/react/src/components/material/organisms/DeleteConfirmationModal.js
  src/templates/vue/src/components/organisms/Navbar.vue
  src/themeTemplates/react-themes/dark-theme.js
  src/themeTemplates/vue-themes/dark-theme.vue
Labels: Improvement, Under Review

#162 159/ Added dark theme in angular application
  src/index.js
  src/ngrxTemplates/add-user-modal/add-user-modal.component.html
  src/questionnaire.js
  src/templates/angular/angular.json
  src/templates/angular/src/app/pages/header/header.component.css
  src/templates/angular/src/app/pages/header/header.component.html
  src/templates/angular/src/app/pages/header/header.component.ts
  src/templates/angular/src/app/pages/users/users.component.html
  src/templates/angular/src/app/shared/shared.module.ts
  src/templates/angular/src/index.html
  src/templates/angular/src/styles.css
  src/themeTemplates/angular-themes/dark-theme.css
Labels: Enhancement, Under Review

#149 144/Add Cypress Testing Framewok - POC
  src/constants.js
  src/index.js
  src/questionnaire.js
  src/uiTests/CypressTests/TestScripts/cypress/e2e/app.cy.js
  src/uiTests/CypressTests/TestScripts/cypress/support/commands.js
  src/uiTests/CypressTests/TestScripts/cypress/support/e2e.js
  src/uiTests/CypressTests/cypress.config.js
  src/utils/createDbConn.js
  src/utils/createEmailSevice.js
  src/utils/createLogger.js
  src/utils/helper.js
Labels: POC

#164 Integrate Auth0 for vue app.
  src/constants.js
  src/envTemplates/.authEnv
  src/envTemplates/.dbEnv
  src/index.js
  src/questionnaire.js
  src/templates/vue/src/App.css
  src/templates/vue/src/App.vue
  src/templates/vue/src/components/atoms/LogoutButton.vue
  src/templates/vue/src/components/organisms/Navbar.vue
  src/templates/vue/src/main.js
  src/templates/vue/src/router/index.js
Labels: Improvement, Under Review

#135 127/dark mode issue on reload
  src/index.js
  src/templates/react/src/components/bootstrap/organisms/NavBar.js
  src/templates/vue/src/components/organisms/Navbar.vue
  src/themeProviderTemplates/react-themes/theme.js
  src/themeProviderTemplates/theme.constants.js
  src/themeProviderTemplates/vue-themes/light-dark-theme.vue
  src/themeTemplates/react-themes/dark-theme.js
  src/themeTemplates/vue-themes/dark-theme.vue
Labels: Bug, Under Review

#169 167/Refactor-appjs-file-and-fix-issues
  src/authTemplates/oktaTemplate/Home.jsx
  src/index.js
  src/templates/angular/src/app/pages/header/header.component.css
  src/templates/angular/src/app/pages/header/header.component.html
  src/templates/angular/src/app/pages/header/header.component.ts
  src/templates/angular/src/index.html
  src/templates/angular/src/styles.css
  src/templates/react/README.md
  src/templates/react/package.json
  src/templates/react/src/App.css
  src/templates/react/src/App.js
  src/templates/react/src/components/bootstrap/organisms/NavBar.js
  src/templates/react/src/components/material/organisms/DeleteConfirmationModal.js
  src/templates/react/src/components/material/organisms/NavBar.js
  src/templates/vue/src/App.css
  src/templates/vue/src/components/organisms/Navbar.vue
  src/themeProviderTemplates/react-themes/theme.js
  src/utils/helper.js
Labels: Enhancement, Ready

#170 165/Fix issues in Bootstrap style classes for vue3 app.
  src/templates/vue/package.json
  src/templates/vue/src/App.vue
  src/templates/vue/src/components/organisms/Modal.vue
  src/templates/vue/src/components/organisms/Table.vue
  src/templates/vue/src/main.js
  src/templates/vue/src/styles/dark-theme.css
  src/templates/vue/src/styles/index.css
  src/themeProviderTemplates/vue-themes/theme.vue
  src/vuexTemplates/userModal/AddUser.vue
  src/vuexTemplates/userModal/DeleteUser.vue
  src/vuexTemplates/userModal/EditUser.vue
Labels: Bug, Ready

#152 148/integrate okta in angular
  src/index.js
  src/questionnaire.js
  src/templates/angular/src/app/app-routing.module.ts
  src/templates/angular/src/app/app.module.ts
  src/templates/angular/src/app/pages/header/header.component.html
  src/templates/angular/src/app/pages/header/header.component.ts
  src/themeTemplates/angular-themes/dark-theme.css
Labels: Enhancement, Ready

#176 Added question enter destination folder path
  src/generateRoutes/generate-route.js
  src/generateScreens/generate-react-screen.js
  src/index.js
  src/questionnaire.js
  src/utils/helper.js
Labels: Ready

#173 171/conditionally injection of dependencies
  src/constants.js
  src/dependencies.js
  src/index.js
  src/scripts.js
  src/templates/react/package.json
  src/templates/vue/src/styles/index.css
  src/themeProviderTemplates/angular-themes/dark-theme.css
  src/utils/createDbConn.js
  src/utils/createEmailSevice.js
  src/utils/createLogger.js
  src/utils/helper.js
Labels: Ready for review., Improvement

#178 177/Update Navbar & Table component to be responsive for vue app.
  src/templates/node-js/controllers/controller.js
  src/templates/vue/src/components/atoms/Button.vue
  src/templates/vue/src/components/organisms/Modal.vue
  src/templates/vue/src/components/organisms/Navbar.vue
  src/templates/vue/src/components/organisms/Table.vue
  src/themeProviderTemplates/vue-themes/theme.vue
  src/vuexTemplates/userModal/AddUser.vue
  src/vuexTemplates/userModal/EditUser.vue
Labels: Improvement, Ready

#185 139/Integrate Okta authentication for vue app.
  src/constants.js
  src/dependencies.js
  src/envTemplates/.oktaEnv
  src/index.js
  src/templates/vue/src/App.vue
  src/templates/vue/src/components/atoms/LogoutButton.vue
  src/templates/vue/src/components/organisms/Navbar.vue
  src/templates/vue/src/main.js
  src/templates/vue/src/pages/Home.vue
  src/templates/vue/src/router/index.js
  src/utils/helper.js
Labels: Enhancement, Ready

#179 Implement Auth0 for Angular app
  src/dependencies.js
  src/index.js
  src/templates/angular/src/app/app-routing.module.ts
  src/templates/angular/src/app/app.module.ts
  src/templates/angular/src/app/pages/header/header.component.html
  src/templates/angular/src/app/pages/header/header.component.ts
Labels: Enhancement, Ready

#184 93/Implemented reusable table component for angular application.
  src/ngrxTemplates/add-user-modal/add-user-modal.component.html
  src/templates/angular/src/app/pages/users/users.component.html
  src/templates/angular/src/app/pages/users/users.component.ts
  src/templates/angular/src/app/shared/components/atoms/button/button.component.css
  src/templates/angular/src/app/shared/components/atoms/button/button.component.html
  src/templates/angular/src/app/shared/components/atoms/button/button.component.spec.ts
  src/templates/angular/src/app/shared/components/atoms/button/button.component.ts
  src/templates/angular/src/app/shared/components/atoms/datepicker/datepicker.component.css
  src/templates/angular/src/app/shared/components/atoms/datepicker/datepicker.component.html
  src/templates/angular/src/app/shared/components/atoms/datepicker/datepicker.component.spec.ts
  src/templates/angular/src/app/shared/components/atoms/datepicker/datepicker.component.ts
  src/templates/angular/src/app/shared/components/atoms/input/input.component.css
  src/templates/angular/src/app/shared/components/atoms/input/input.component.html
  src/templates/angular/src/app/shared/components/atoms/input/input.component.spec.ts
  src/templates/angular/src/app/shared/components/atoms/input/input.component.ts
  src/templates/angular/src/app/shared/components/atoms/label/label.component.css
  src/templates/angular/src/app/shared/components/atoms/label/label.component.html
  src/templates/angular/src/app/shared/components/atoms/label/label.component.spec.ts
  src/templates/angular/src/app/shared/components/atoms/label/label.component.ts
  src/templates/angular/src/app/shared/components/molecules/table/table.component.css
  src/templates/angular/src/app/shared/components/molecules/table/table.component.html
  src/templates/angular/src/app/shared/components/molecules/table/table.component.spec.ts
  src/templates/angular/src/app/shared/components/molecules/table/table.component.ts
  src/templates/angular/src/app/shared/shared.module.ts
  src/themeProviderTemplates/angular-themes/dark-theme.css
Labels: Improvement, Ready

#166 161/fix UI issues in react app
  src/authTemplates/oktaTemplate/Home.jsx
  src/questionnaire.js
  src/reduxTemplates/userform/AddUserForm.js
  src/reduxTemplates/userform/Adduser.js
  src/reduxTemplates/usersModal/ShowDetails.js
  src/templates/react/src/App.css
  src/templates/react/src/App.js
  src/templates/react/src/components/bootstrap/organisms/NavBar.js
  src/templates/react/src/components/material/organisms/NavBar.js
  src/templates/react/src/screens/Users/Users.js
Labels: Enhancement, Ready

#188 187/fix functionality issues on develop branch
  src/index.js
  src/utils/createDbConn.js
Labels: Bug, Ready

#183 181/ Integrated winston-logger-service
  src/index.js
  src/logger/template/winston.js
  src/logger/winston.js
Labels: Enhancement, Ready

#189 186/Integrate jest test framework for vue app.
  src/constants.js
  src/dependencies.js
  src/index.js
  src/scripts.js
  src/uiTests/CypressTests/TestScripts/cypress/e2e/app.cy.js
  src/uiTests/CypressTests/cypress.config.js
  src/uiTests/CypressTests/cypress.constants.js
  src/uiTests/JestTests/TestScripts/app.spec.js
  src/uiTests/JestTests/jest.config.js
  src/utils/helper.js
  src/utils/projectExecutionCommands.js
Labels: Enhancement, Ready

#193 190/fix-issue-of-reloading-data
  src/logger/template/winston.js
  src/reduxTemplates/userform/AddUserForm.js
  src/templates/react/src/components/material/organisms/DeleteConfirmationModal.js
  src/templates/react/src/screens/Users/Users.js
Labels: Bug, Ready

#194 Fixed console message issue.
  src/utils/projectExecutionCommands.js
Labels: Bug, Ready

#196 fix-issues-in-model-footer-and-close-buttons
  src/dependencies.js
  src/reduxTemplates/userform/Adduser.js
  src/templates/react/src/components/bootstrap/organisms/Modal.js
Labels: Bug, Ready

#199 198/Updated dynamic default route for backend data table name for user
  src/angularApiTemplates/add-user-modal/add-user-modal.component.html
  src/angularApiTemplates/base-url.ts
  src/angularApiTemplates/services/base-url.ts
  src/angularApiTemplates/services/services.ts
  src/index.js
  src/themeProviderTemplates/angular-themes/dark-theme.css
Labels: Improvement, Under Internal Review

#151 147/show user name in the header after login using Okta in React & Angular app.
  src/authTemplates/oktaTemplate/Home.jsx
  src/templates/angular/src/app/app-routing.module.ts
  src/templates/angular/src/app/app.module.ts
  src/templates/angular/src/app/pages/header/header.component.css
  src/templates/angular/src/app/pages/header/header.component.html
  src/templates/angular/src/app/pages/header/header.component.ts
  src/templates/angular/src/environments/environment.ts
  src/templates/node-js/controllers/controller.js
  src/themeProviderTemplates/angular-themes/dark-theme.css
Labels: Enhancement, Ready

#201 200/Add Readme file for vue app.
  src/index.js
  src/templates/vue/README.md
  src/utils/helper.js
Labels: Enhancement, Ready

#197 182/Integrate Sentry Logger Service.
  src/logger/template/sentry.js
  src/logger/template/winston.js
  src/templates/node-js/controllers/controller.js
  src/templates/node-js/routes/route.js
  src/utils/createLogger.js
Labels: Enhancement, Ready

#203 202/Integrate Mocha test framework for vue app.
  src/constants.js
  src/dependencies.js
  src/index.js
  src/scripts.js
  src/templates/vue/src/components/organisms/Modal.vue
  src/uiTests/MochaTests/.eslintrc.js
  src/uiTests/MochaTests/TestScripts/example.spec.js
  src/utils/helper.js
  src/vuexTemplates/userModal/EditUser.vue
Labels: Enhancement, Under Internal Review

#208 207/Add README and Prettier for angular app
  src/index.js
  src/questionnaire.js
  src/templates/angular/.prettierignore
  src/templates/angular/.prettierrc.json
  src/templates/angular/README.md
  src/templates/angular/package.json
Labels: Enhancement, Ready

#215 Resolved comment react
  src/generateRoutes/generate-route.js
  src/questionnaire.js
  src/templates/node-js/controllers/controller.js
  src/templates/node-js/routes/route.js
  src/utils/helper.js
Labels: Bug, Ready

#205 204/fix code formatting issue in react app
  src/index.js
  src/reduxTemplates/userform/AddUserForm.js
  src/reduxTemplates/userform/Adduser.js
  src/scripts.js
  src/templates/node-js/.prettierignore
  src/templates/node-js/package.json
  src/templates/node-js/routes/route.js
  src/templates/react/.prettierignore
  src/templates/react/package.json
  src/templates/react/src/helper/index.js
  src/utils/helper.js
Labels: Bug, Ready

#219 Kept EJS Render in separate file
  src/index.js
  src/utils/handleRenderEJS.js
Labels: Improvement, Ready

#214 Updated DeleteConfirmation modal
  src/index.js
  src/reduxTemplates/userform/AddUserForm.js
  src/reduxTemplates/userform/Adduser.js
  src/reduxTemplates/userform/DeleteConfirmationModal.js
  src/templates/react/src/App.css
  src/templates/react/src/components/bootstrap/organisms/DeleteConfirmationModal.js
  src/templates/react/src/components/bootstrap/organisms/Table.js
  src/templates/react/src/screens/Users/Users.js
Labels: Bug, Ready

#222 220/Integrate nightwatch test framework for all.
  src/dependencies.js
  src/index.js
  src/questionnaire.js
  src/scripts.js
  src/templates/angular/src/app/app.component.html
  src/templates/react/src/App.js
  src/uiTests/NightwatchTests/TestScripts/test.js
  src/uiTests/NightwatchTests/nightwatch.conf.js
  src/uiTests/NightwatchTests/nightwatch.config.js
  src/utils/helper.js
Labels: Enhancement, Ready

#223 217/Implement docker for (react and angular) app
  src/dockerTemplate/angular-docker/.dockerignore
  src/dockerTemplate/angular-docker/Dockerfile
  src/dockerTemplate/db-docker-compose.yml
  src/dockerTemplate/docker-compose.yml
  src/dockerTemplate/react-docker/.dockerignore
  src/dockerTemplate/react-docker/Dockerfile
  src/dockerTemplate/vue-docker/.dockerignore
  src/dockerTemplate/vue-docker/Dockerfile
  src/index.js
  src/questionnaire.js
  src/templates/angular/src/app/app.module.ts
  src/templates/angular/src/app/pages/header/header.component.ts
  src/templates/angular/src/app/pages/users/users.component.ts
  src/templates/angular/src/environments/environment.ts
  src/utils/helper.js
Labels: Enhancement, Ready

#221 211/Add 'READ_ME.md' for react app
  src/templates/react/README.md
Labels: Enhancement, Ready

#229 225/Add Validation for questionnaire.
  src/questionnaire.js
  src/templates/vue/src/components/atoms/Button.vue
  src/utils/validators.js
  src/vuexTemplates/userModal/AddUser.vue
  src/vuexTemplates/userModal/EditUser.vue
Labels: Bug, Under Internal Review

#234 Add css tailwindcss framework for angular app
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.css
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.html
  src/constants.js
  src/dependencies.js
  src/index.js
  src/ngrxTemplates/user-actions-modal/user-actions-modal.component.css
  src/ngrxTemplates/user-actions-modal/user-actions-modal.component.html
  src/questionnaire.js
  src/tailwindCssTemplates/tailwind.config.js
  src/templates/angular/angular.json
  src/templates/angular/package.json
  src/templates/angular/src/app/pages/header/header.component.css
  src/templates/angular/src/app/pages/header/header.component.html
  src/templates/angular/src/app/pages/header/header.component.ts
  src/templates/angular/src/app/pages/home/home.component.html
  src/templates/angular/src/app/pages/users/users.component.html
  src/templates/angular/src/app/pages/users/users.component.ts
  src/templates/angular/src/app/shared/components/molecules/table/table.component.html
  src/templates/angular/src/styles.css
  src/themeProviderTemplates/angular-themes/dark-theme.css
  src/utils/helper.js
Labels: Enhancement, Ready

#233 224/Integrate Azure blob service.
  src/blobTemplates/azure.js
  src/envTemplates/.dbEnv
  src/index.js
  src/templates/node-js/index.js
  src/templates/vue/README.md
  src/utils/createBlobService.js
  src/utils/helper.js
Labels: Enhancement, Under Internal Review

#236 228/automate qa of tavajs
  src/answersEvaluator.js
  src/index.js
  src/inquirerExecutor.js
  test/test.spec.js
Labels: help wanted

#246 226/Implement cognito for angular app
  src/answersEvaluator.js
  src/dependencies.js
  src/templates/angular/src/app/app.component.html
  src/templates/angular/src/app/app.component.ts
  src/templates/angular/src/app/app.module.ts
  src/templates/angular/src/app/pages/header/header.component.css
  src/templates/angular/src/app/pages/header/header.component.html
  src/templates/angular/src/app/pages/header/header.component.ts
  src/templates/angular/src/environments/environment.ts
  src/templates/angular/src/polyfills.ts
  src/templates/angular/src/styles.css
  src/themeProviderTemplates/angular-themes/dark-theme.css
Labels: Enhancement, Ready

#240 216/Integrated cognito authentication service for vue app.
  src/answersEvaluator.js
  src/dependencies.js
  src/envTemplates/.cognitoEnv
  src/templates/vue/README.md
  src/templates/vue/src/App.vue
  src/templates/vue/src/components/atoms/LogoutButton.vue
  src/templates/vue/src/components/organisms/Navbar.vue
  src/templates/vue/src/main.js
Labels: Enhancement, Ready

#249 248/Update readme for tava js
  README.md
Labels: Improvement, Ready

#247 232/Integrate sendgrid in nodejs
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.css
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.html
  src/answersEvaluator.js
  src/constants.js
  src/emailTemplates/sendgrid.js
  src/envTemplates/.dbEnv
  src/ngrxTemplates/user-actions-modal/user-actions-modal.component.css
  src/ngrxTemplates/user-actions-modal/user-actions-modal.component.html
  src/templates/node-js/controllers/controller.js
  src/utils/helper.js
Labels: Enhancement, Ready

#250 241/Integrate AWS S3 blob service.
  src/blobTemplates/aws-s3.js
  src/envTemplates/.dbEnv
  src/templates/node-js/index.js
  src/templates/vue/README.md
  src/utils/createBlobService.js
Labels: Enhancement, Ready

#256 254/Update for cypress run command script
  src/scripts.js
Labels: Improvement, Under Internal Review

#239 Added cognito authentication for react app
  src/answersEvaluator.js
  src/constants.js
  src/dependencies.js
  src/templates/react/README.md
  src/templates/react/src/App.js
  src/templates/react/src/components/bootstrap/organisms/NavBar.js
  src/templates/react/src/components/material/organisms/NavBar.js
  src/templates/react/src/index.js
Labels: Enhancement, Ready

#264 228/Updated CLI messages and added spinner
  package.json
  src/answersEvaluator.js
  src/utils/converters.js
  src/utils/projectExecutionCommands.js
  src/utils/projectInfo.js
  src/utils/projectSetUp.js
Labels: Improvement, Ready

#243 238/update table and deleteconfirmation modal of mui in react
  src/answersEvaluator.js
  src/dependencies.js
  src/reduxTemplates/userform/AddUserForm.js
  src/reduxTemplates/userform/Adduser.js
  src/reduxTemplates/userform/DeleteConfirmationModal.js
  src/templates/react/src/components/material/organisms/DeleteConfirmationModal.js
  src/templates/react/src/components/material/organisms/Table.js
  src/templates/react/src/screens/Users/Users.js
Labels: Bug, Ready

#257 242/Integrate Amazon SES email service.
  src/answersEvaluator.js
  src/constants.js
  src/dependencies.js
  src/emailTemplates/Amazon_ses.js
  src/envTemplates/.dbEnv
  src/envTemplates/.sesEnv
  src/templates/node-js/controllers/controller.js
  src/templates/node-js/index.js
  src/templates/vue/README.md
  src/uiTests/MochaTests/.eslintrc.js
  src/utils/createEmailSevice.js
  src/utils/helper.js
Labels: Enhancement, Under Internal Review

#253 251/Add Validation in user modal button.
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.html
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.ts
  src/ngrxTemplates/user-actions-modal/user-actions-modal.component.html
  src/ngrxTemplates/user-actions-modal/user-actions-modal.component.ts
  src/templates/angular/src/app/pages/home/home.component.html
  src/templates/angular/src/app/pages/users/users.component.html
  src/templates/angular/src/app/pages/users/users.component.ts
  src/templates/angular/src/app/shared/components/atoms/button/button.component.css
  src/templates/angular/src/app/shared/components/atoms/button/button.component.html
  src/templates/angular/src/app/shared/components/atoms/button/button.component.ts
Labels: Improvement, Ready

#276 Fix generate tava not working in the updated directory structure
  src/index.js
Labels: Bug, Ready

#272 230/Add tailwind CSS framework for react app
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.html
  src/answersEvaluator.js
  src/constants.js
  src/dependencies.js
  src/ngrxTemplates/user-actions-modal/user-actions-modal.component.html
  src/questionnaire.js
  src/reduxTemplates/userform/AddUserForm.js
  src/reduxTemplates/userform/Adduser.js
  src/reduxTemplates/userform/DeleteConfirmationModal.js
  src/reduxTemplates/usersModal/ShowDetails.js
  src/reduxTemplates/widgets/modal/Modal.js
  src/tailwindCssTemplates/angular/tailwind.config.js
  src/tailwindCssTemplates/react/postcss.config.js
  src/tailwindCssTemplates/react/tailwind.config.js
  src/templates/angular/angular.json
  src/templates/angular/src/app/pages/header/header.component.css
  src/templates/angular/src/app/pages/header/header.component.html
  src/templates/angular/src/app/pages/header/header.component.ts
  src/templates/angular/src/app/pages/users/users.component.html
  src/templates/angular/src/app/pages/users/users.component.ts
  src/templates/angular/src/app/shared/components/molecules/table/table.component.html
  src/templates/angular/src/styles.css
  src/templates/react/README.md
  src/templates/react/src/App.js
  src/templates/react/src/components/tailwind/atoms/Button.js
  src/templates/react/src/components/tailwind/atoms/Checkbox.js
  src/templates/react/src/components/tailwind/atoms/Datepicker.js
  src/templates/react/src/components/tailwind/atoms/File.js
  src/templates/react/src/components/tailwind/atoms/Input.js
  src/templates/react/src/components/tailwind/atoms/Label.js
  src/templates/react/src/components/tailwind/atoms/Select.js
  src/templates/react/src/components/tailwind/molecules/InputGroup.js
  src/templates/react/src/components/tailwind/organisms/Modal.js
  src/templates/react/src/components/tailwind/organisms/NavBar.js
  src/templates/react/src/components/tailwind/organisms/Table.js
  src/templates/react/src/index.css
  src/templates/react/src/screens/Users/Users.js
  src/themeProviderTemplates/react-themes/theme.js
  src/utils/helper.js
Labels: Enhancement, Ready

#268 276/Fixed issue of duplicate env files
  src/envTemplates/.amazon_ses
  src/envTemplates/.sendgridEnv
  src/envTemplates/.smtpEnv
  src/utils/createEmailSevice.js
Labels: Bug, Ready

#263 262/Implement network status handling for angular app
  src/answersEvaluator.js
  src/questionnaire.js
  src/templates/angular/src/app/app.component.css
  src/templates/angular/src/app/app.component.html
  src/templates/angular/src/app/app.component.ts
  src/utils/helper.js
  src/utils/projectSetUp.js
Labels: Enhancement, Ready

#277 261/Add dark mode for tailwind CSS framework in vue app.
  src/answersEvaluator.js
  src/tailwindCssTemplates/vue/tailwind.config.js
  src/templates/vue/src/App.vue
  src/templates/vue/src/bootstrap/components/atoms/Button.vue
  src/templates/vue/src/bootstrap/components/atoms/Input.vue
  src/templates/vue/src/bootstrap/components/atoms/Label.vue
  src/templates/vue/src/bootstrap/components/atoms/LogoutButton.vue
  src/templates/vue/src/bootstrap/components/organisms/Modal.vue
  src/templates/vue/src/bootstrap/components/organisms/Navbar.vue
  src/templates/vue/src/bootstrap/components/organisms/Table.vue
  src/templates/vue/src/bootstrap/pages/Home.vue
  src/templates/vue/src/bootstrap/pages/Users.vue
  src/templates/vue/src/bootstrap/styles/dark-theme.css
  src/templates/vue/src/bootstrap/styles/index.css
  src/templates/vue/src/components/tailwind/atoms/Button.vue
  src/templates/vue/src/components/tailwind/organisms/Navbar.vue
  src/templates/vue/src/components/tailwind/pages/Home.vue
  src/templates/vue/src/components/tailwind/userModal/EditUser.vue
  src/templates/vue/src/components/tailwind/userModal/ShowUsers.vue
  src/templates/vue/src/main.js
  src/templates/vue/src/router/index.js
  src/templates/vue/src/tailwind/components/atoms/Button.vue
  src/templates/vue/src/tailwind/components/atoms/Input.vue
  src/templates/vue/src/tailwind/components/atoms/Label.vue
  src/templates/vue/src/tailwind/components/atoms/LogoutButton.vue
  src/templates/vue/src/tailwind/components/organisms/Modal.vue
  src/templates/vue/src/tailwind/components/organisms/Navbar.vue
  src/templates/vue/src/tailwind/components/organisms/Table.vue
  src/templates/vue/src/tailwind/pages/Home.vue
  src/templates/vue/src/tailwind/pages/Users.vue
  src/templates/vue/src/tailwind/styles/index.css
  src/themeProviderTemplates/vue-themes/theme.vue
  src/vuexTemplates/bootstrap/userModal/AddUser.vue
  src/vuexTemplates/bootstrap/userModal/DeleteUser.vue
  src/vuexTemplates/bootstrap/userModal/EditUser.vue
  src/vuexTemplates/bootstrap/userModal/ShowUsers.vue
  src/vuexTemplates/tailwind/userModal/AddUser.vue
  src/vuexTemplates/tailwind/userModal/DeleteUser.vue
  src/vuexTemplates/tailwind/userModal/EditUser.vue
  src/vuexTemplates/tailwind/userModal/ShowUsers.vue
Labels: Enhancement, In Progress

#278 275/Refactored angular application
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.css
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.html
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.spec.ts
  src/angularApiTemplates/user-actions-modal/user-actions-modal.component.ts
  src/answersEvaluator.js
  src/constants.js
  src/ngrxTemplates/user-actions-modal/user-actions-modal.component.ts
  src/utils/helper.js
Labels: Improvement, Ready

#279 Integrate jest test framework for react app
  src/answersEvaluator.js
  src/dependencies.js
  src/scripts.js
  src/templates/react/package.json
  src/templates/react/src/App.test.js
  src/templates/react/src/setupTests.js
  src/uiTests/JestTests/TestScripts/app.spec.js
Labels: Enhancement, Ready

#281 271/Implement network status handling for vue app.
  src/questionnaire.js
  src/templates/vue/src/App.vue
  src/templates/vue/src/components/NetworkStatus.vue
  src/templates/vue/src/styles/index.css
  src/templates/vue/src/styles/network-status.css
Labels: Enhancement, Ready

#289 285/Fix karma test case failed in angular application
  src/Frameworks/WebFrameworks/angular/src/app/app.component.spec.ts
  src/Frameworks/WebFrameworks/angular/src/app/pages/header/header.component.spec.ts
  src/Frameworks/WebFrameworks/angular/src/app/pages/users/users.component.spec.ts
  src/Frameworks/WebFrameworks/angular/src/app/shared/components/atoms/datepicker/datepicker.component.spec.ts
  src/StateManagement/ngrxTemplates/store/action/user.actions.spec.ts
  src/StateManagement/ngrxTemplates/user-actions-modal/user-actions-modal.component.spec.ts
Labels: Bug, Ready

#287 Fix issue not found controllers and routes in NodeJS application
  src/utils/helper.js
Labels: Bug, Ready

#288 280/Implement network status handling for react app
  src/Frameworks/WebFrameworks/react/src/App.js
  src/Frameworks/WebFrameworks/react/src/index.css
  src/Services/NetworkInformerServices/react/NetworkStatus.js
  src/TavaJsExecutors/answersEvaluator.js
  src/TavaJsExecutors/constants.js
  src/utils/helper.js
Labels: Enhancement, Ready
